#!/bin/bash
# Show scrapped data
# Kabouik
# Dependencies: jello, jtbl, jq

cat "$1" | jello '\
result = []
for d, l, t, x in zip(_.Date, _.Location, _.Title, _.Details):
    result.append({"Date": d, "Location": l, "Title": t, "Details": x})
    result' | jtbl
